#%RAML 1.0 NamedExample

   [{
              "productid": 1,
              "catagoryid": 13,
              "name": "HP",
              "description": "core i7",
              "video_url":"www.hp.com",
              "price": 7000

               },
               {
              "productid": 2,
              "catagoryid": 13,
              "name": "Dell",
              "description": "core i3",
              "video_url":"www.dell.com",
              "price": 4000

               }]