#%RAML 1.0 NamedExample

   {
              "productid": 1,
              "catagoryid": 13,
              "name": "HP",
              "description": "core i7",
              "video_url":"www.hp.com",
              "price": 7000

    }